#!/bin/bash

function agenda() {
    if [[ -e ~/tmp/agenda.txt ]]; then
        echo -e "\e[1;31m`date`\e[0m";
        cat ~/tmp/agenda.txt;
    fi;
}

function todo() {
    if [[ -e ~/.taskrc ]]; then
        echo "Tasks:"; task list | head -n -2 | tail -n +2
    fi;
}

agenda
todo
