#!/bin/bash

POWER="⚡"
EMPTY_HEART="♡"
FULL_HEART="♥"

function battery_status() {
    paths=$( eval echo /sys/class/power_supply/BAT*/$@ )
    cat $paths 2> /dev/null | \
        paste -d+ -s - | \
        bc -l 
}

function repeat() {
    eval printf -- '$1%.s' {1..$2}
}

if [[ -z "$1" ]]; then
    num_stars=5
else
    num_stars=$1
fi
curr_battery=$( battery_status "{charge,energy}_now" )
full_battery=$( battery_status "{charge,energy}_full" )
percent=$( echo "$curr_battery / $full_battery" | bc -l )
charging=$( cat /sys/class/power_supply/AC/online )

# Add 0.5 so that we are rounding instead of just
# truncating the number of hearts
full_hearts=$( echo "($num_stars * $percent + 0.5)/1" | bc )
empty_hearts=$( echo "($num_stars - $full_hearts)/1" | bc )

[ $charging == 1 ] && echo -n $POWER
[ "$full_hearts" -gt 0 ] && repeat $FULL_HEART $full_hearts
[ "$empty_hearts" -gt 0 ] && repeat $EMPTY_HEART $empty_hearts
