#!/bin/bash

POWER="⚡"
CHARS="♥♡♥"

function battery_status() {
    paths=$( eval echo /sys/class/power_supply/BAT*/$@ )
    cat $paths 2> /dev/null | \
        paste -d+ -s - | \
        bc -l 
}

function repeat() {
    eval printf -- '$1%.s' {1..$2}
}

if [[ -z "$1" ]]; then
    num_stars=5
else
    num_stars=$1
fi

if ! compgen -G "/sys/class/power_supply/BAT*" > /dev/null; then
    echo '🔌'
    exit
fi

curr_battery=$( battery_status "{charge,energy}_now" )
full_battery=$( battery_status "{charge,energy}_full" )
percent=$( echo "$curr_battery / $full_battery" | bc -l )
charging=$( cat /sys/class/power_supply/AC*/online )

[[ $charging == 1 ]] && echo -n $POWER
progress --characters="$CHARS" --progress=$curr_battery --max-progress=$full_battery --width=$num_stars
