#!/usr/bin/env python3

from __future__ import print_function
import sys
import os
import glob

BRIGHT_PATH = glob.glob("/sys/class/backlight/*").pop()

def usage():
    print(
        """{} [-+][percent][%] 
    Modify system brightness.""".format(
            sys.argv[0]
        )
    )
    return


if __name__ == "__main__":
    command = sys.argv[1]
    direction = command[0]
    if direction not in "+-":
        usage()
        print("Must preface percent with - or +")
        sys.exit(-1)
    try:
        tmp = command[1:].replace("%", "")
        percent_float = float(tmp)
    except ValueError:
        usage()
        print("Invalid percent")
        sys.exit(-1)

    percent_str = f"{percent_float}%"
    if direction == "+":
        percent_str = f"+{percent_str}"
    else:
        percent_str = f"{percent_str}-"

    os.system(f"bash -c 'brightnessctl set {percent_str}' > /dev/null")

    max_brightness = int(open(os.path.join(BRIGHT_PATH, "max_brightness")).read())
    new_brightness = int(open(os.path.join(BRIGHT_PATH, "brightness")).read())

    new_percent = int(100 * new_brightness / max_brightness)
    print("{:d}%".format(new_percent), end="", flush=True)
    os.system(
        f"bash -c 'progress --characters=■□◧  --progress={new_percent} --width=20'"
    )
