#!/bin/bash

if command -v google-chrome; then
    eval google-chrome --incognito $@
elif command -v chromium; then
    eval chromium --incognito $@
elif command -v firefox; then
    eval firefox --private-window $@
fi

echo "No chromium based browser found"
exit 1
