#!/bin/bash

VOLUME_BOX=${VOLUME_BOX:-"\u25a0"}
OVERVOL_BOX=${OVERVOL_BOX:-"\u25cf"}
EMPTY_BOX=${EMPTY_BOX:-"\u25a1"}
MUTE_BOX=${MUTE_BOX:-"\u25a8"}

action=$1
num_boxes=${2:-10}

function repeat() {
    eval printf -- '$1%.s' {1..$2}
}

if [[ "$action" != "status" ]]; then
    if [[ "$action" == "toggle" ]]; then
        pulsemixer --toggle-mute
    elif [ ! -z "$action" ]; then
        pulsemixer --change-volume $action
    fi
fi

IS_MUTE=$( pulsemixer --get-mute )
VOLUME=$( pulsemixer --get-volume | cut -d' ' -f1 )

if [ "$IS_MUTE" -eq "1" ]; then
    CHARS="▨□◫"
else
    CHARS="■□◧"
fi

echo -ne "$VOLUME%"
progress --characters="$CHARS" --progress=$VOLUME --width=20
