#!/bin/bash
# Must install and configure gcal-cli in addition to the crontab:
# */15 * * * * python -m gcalcli.cli agenda "$( date -I )" "$( date --date='2day' -I )" > ~/tmp/agenda.txt

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. ${SCRIPT_DIR}/utils
noglob ensure-crontab "agenda" '*/15 * * * * '$( which pyenv )' exec python -m gcalcli.cli agenda "$( date -I )" "$( date --date=2day -I )" > ~/tmp/agenda.txt 2> ~/tmp/agenda.txt.log' > /dev/null 2>&1 &

function agenda() {
    if [[ -e ~/tmp/agenda.txt ]]; then
        display-center "${COLOR_BRIGHT}${COLOR_RED}${COLOR_UNDERLINE}$(date)${COLOR_NORMAL}"
        if [ -z $1 ]; then
            cat ~/tmp/agenda.txt
        else
            cat ~/tmp/agenda.txt | head -n $1
        fi
        draw-horizline
    fi;
}

if is-term; then
    agenda 10
fi
