#!/bin/bash
# Must install and configure gcal-cli in addition to the crontab:
# */10 * * * * python -m gcalcli.cli agenda "$( date )" "$(date --date='2day')" > ~/tmp/agenda.txt

function agenda() {
    if [[ -e ~/tmp/agenda.txt ]]; then
        echo -e "\e[1;31m`date`\e[0m";
        cat ~/tmp/agenda.txt | tail -n +2 | head -n -1;
    fi;
}

agenda
