#!/bin/sh

function add-ruby-path {
    basepath=$1
    if [ -d $basepath ]; then
        for ruby in $( find $basepath -maxdepth 2 -type d -name bin ); do
            export PATH="$PATH:$ruby"
        done
    fi
}

add-ruby-path "$HOME/.gem/ruby"
add-ruby-path "$HOME/.local/share/gem/ruby"

unset -f add-ruby-path
