#!/bin/bash
# Must install python application `showsnearme` (http://github.com/mynameisfiber/showsnearme) and the crontab:
# */15 * * * * /usr/local/bin/showsnearme -A 2 --hide-url '<ADDRESS>' > $HOME/tmp/shows.txt

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. ${SCRIPT_DIR}/utils
noglob ensure-crontab "showsnearme" '0 * * * * '$( which pyenv )' exec python -m showsnearme.cli -A 2 --hide-url --terminal-link > $HOME/tmp/shows.txt 2> $HOME/tmp/shows.txt.log'  > /dev/null 2>&1 &

function shows() {
    if [[ -e $HOME/tmp/shows.txt ]]; then
        echo "$(tput setaf 2)Events near me$(tput sgr0)"
        cat $HOME/tmp/shows.txt | sed '/^\s*$/d';
        draw-horizline
    fi;
}

if is-term ; then
    shows
fi
