#!/bin/bash

function activate() {
    if [ -e ./venv/bin/activate ]; then
        echo "Activating virtualenv."
        source ./venv/bin/activate
    elif [[ -e ./.venv/bin/activate && "$PIPENV_ACTIVE" -ne "1" ]]; then
        source ./.venv/bin/activate
    fi
}

if [[ $TMUX ]]; then
    activate;
fi
